### ISSUE TITLE
can you help me find whether a number is prime or not?

### ISSUE THREAD

**Issue by imox2** [ddkhirwar/python-adventure#1]
I need prime numbers for my job. can you write a script to tell whether a number is prime or not? It would greatly help me. Thanks.

**Comment by ddkhirwar** [comment]
I am little busy. I will try to complete it by tomorrow. Thanks.

**Comment by ddkhirwar** [comment]
Done.

**Comment by imox2** [comment]
Thanks for the code. But I have a problem. I was able to test small numbers like 45, 67,,4322, 53322 . But when I tried to check whether 198732345 is prime. It is taking a long time to check whether it is prime or not. Can you do something about it?

**Comment by ddkhirwar** [comment]
Implemented a faster method of finding prime number. using root n.
